#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
config="
	server_name _;

	location = /redirect {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
"
sudo chmod -R "$USER":"$USER" /etc/nginx/sites-available/
sudo sed -i "/server_name _;/c\ $config" /etc/nginx/sites-available/default
