#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
sudo apt update
# install nginx package
sudo apt install nginx -y
# allow port 80
sudo ufw allow 'Nginx HTTP'
# start nginx
sudo service nginx start
# set www directory owner
sudo chown -R "$USER":"$USER" /var/www
# set default response file
echo 'Hello World!' > /var/www/html/index.html
# change owner
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/
sudo sed -i "/server_name _;/c\ \tserver_name _;\n\tlocation = /redirect_me {\n\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n\t}" /etc/nginx/sites-available/default
# restart nginx
sudo service nginx restart
