#!/usr/bin/env bash
# A custom 404 page that contains the string Ceci n'est pas une page.
sudo apt update
# install nginx package
sudo apt install nginx -y
# allow port 80
sudo ufw allow 'Nginx HTTP'
# start nginx
sudo service nginx start
# set www directory owner
sudo chown -R "$USER":"$USER" /var/www
# set default response file
echo 'Hello World!' > /var/www/html/index.html
# change owner
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/
sudo sed -i "/server_name _;/c\ \tserver_name _;\n\t# define an error page \n\terror_page 404 /404.html;" /etc/nginx/sites-available/default
sudo chown -R "$USER":"$USER" /var/www/
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo chmod 644 /var/www/html/404.html
# restart nginx
sudo service nginx restart
