#!/usr/bin/env bash
# stops 4-to_infinity_and_beyond process.
# shellcheck disable=SC2009
pid="$(ps -u | grep ./4-to_infinity_and_beyond | grep pts/1 | awk '{print $2}')"
if [ "$pid" ]
then
kill "$pid"
fi
